<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17263" started-at="2016-03-21T18:03:21Z" finished-at="2016-03-21T18:03:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17263" started-at="2016-03-21T18:03:21Z" finished-at="2016-03-21T18:03:39Z">
      <class name="ha.exercise2.TestAPI_NREL">
        <test-method status="PASS" signature="TestFindStationID()[pri:0, instance:ha.exercise2.TestAPI_NREL@2cfb4a64]" name="TestFindStationID" duration-ms="14950" started-at="2016-03-21T23:33:21Z" finished-at="2016-03-21T23:33:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestFindStationID -->
        <test-method status="FAIL" signature="TestFindStationAddress()[pri:0, instance:ha.exercise2.TestAPI_NREL@2cfb4a64]" name="TestFindStationAddress" duration-ms="2284" started-at="2016-03-21T23:33:36Z" depends-on-methods="ha.exercise2.TestAPI_NREL.TestFindStationID" finished-at="2016-03-21T23:33:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [208 Barton Springs, Austin, Texas, USA, 78704] but found [208 Barton Springs Rd]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [208 Barton Springs, Austin, Texas, USA, 78704] but found [208 Barton Springs Rd]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at ha.exercise2.TestAPI_NREL.TestFindStationAddress(TestAPI_NREL.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestFindStationAddress -->
      </class> <!-- ha.exercise2.TestAPI_NREL -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
